print ("Welcome to Mad Libs!")

print ("What's your name")

playername = input()
print('')
print ("Hi, "+playername+"!")

print ('Today you will be doing a Mad Lib called "A trip to the Dentist"\n')
print("Let's begin!\n")
lastname1 = input("Enter a last name: ")
adjective1 = input("Enter an Adjective: ")
noun1 = input("Enter a Noun: ")
noun2 = input("Enter another noun: ")
bodypart1 = input("Enter a body part: ")
bodypart2 = input("Enter another body part: ")
pluralnoun1 = input("Enter a plural noun: ")
noun3 = input("Enter a Noun: ")
print("DENTIST: What is your problem, young "+noun1+"?")
print("PATIENT: I have pain in my upper "+noun2+". Which is giving me a severe "+bodypart1+" ache.")
print("DENTIST: Let me take a look. open your "+bodypart2+" wide. "+adjective1+" Good. Now I'm going to tap your "+pluralnoun1+" with my "+noun3+"."'\n')
noun4 = input("Enter another noun: ")
exclaimation = input("Enter an exclaimation: ")
noun5 = input("Enter a Noun: ")
noun6 = input("Enter another noun: ")
noun7 = input("Once more enter a noun: "'\n')
print("PATIENT: Shouldn't you give me a/n "+noun4+" killer.")
print("DENTIST: It's not necessary yet. "+exclaimation+" I think I see a/n "+noun5+" in your upper "+noun6+".")
print("PATIENT: Are you going to pull my "+noun7+" out?"'\n')
verb1 = input("Enter a Verb: ")
noun8 = input("Enter a Noun: ")
adjective2 = input("Enter an Adjective: ")
noun9 = input("Enter a Noun: "'\n')
print("DENTIST: No. I'm going to "+verb1+" your tooth and put it in a temporary "+noun8+".")
print("PATIENT: When do I come back for the "+adjective2+" filling?")
print("DENTIST: A day after I cash your "+noun9+"."'\n')
print ("Congrats, you are done! Yeah, I know, it was long")
print ("but how was your story "+playername+"!"'\n')
print("Thank You for playing!"'\n') 
ans = input("PRESS ENTER TO EXIT")
